# Generated by Django 5.2.5 on 2025-10-05 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_card_image',
            field=models.ImageField(blank=True, null=True, upload_to='kyc_ids/'),
        ),
        migrations.AddField(
            model_name='user',
            name='kyc_status',
            field=models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('PENDING', 'Pending Review'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='UNVERIFIED', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='selfie_image',
            field=models.ImageField(blank=True, null=True, upload_to='kyc_selfies/'),
        ),
    ]
