#
# File: /home/pirate/Documents/Projects/Better-auth/Sheba-Pass/Better-Hack-Sheba-Cred/.github/workflows/ci.yml
#

name: Django CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Tesseract OCR
        run: |
          sudo apt-get update
          sudo apt-get install -y tesseract-ocr

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # --- This is the step that needs to be changed ---
      - name: Run Django tests
        # We add an 'env' block to this step. All variables defined here
        # will be set as environment variables for the duration of the 'run' command.
        env:
          DB_NAME: test_sheba_cred_db
          DB_USER: test_user
          DB_PASS: test_password
          DB_HOST: localhost # For tests, a local service is fine, but we need to specify it.
          DB_PORT: 5432
        run: |
          python manage.py test
